c_compiler:            # [win]
- vs2022               # [win]
cxx_compiler:          # [win]
- vs2022               # [win]
python:
- 3.8.* *_cpython
- 3.9.* *_cpython
- 3.10.* *_cpython
- 3.11.* *_cpython
numpy:
- 1.24
- 1.24
- 1.24
- 1.24
python_impl:
- cpython
- cpython
- cpython
- cpython
